### ISSUE TITLE
Not able to find out the domain rating and URL rating for a site other than "Ahref.com"

### ISSUE THREAD

**Issue by sayalikardile** [Leszek-Sieminski/RAhrefs#5] opened 2020-03-10 18:03 UTC
Dear Leszek, 

When I am trying to run below code chunk using "RAhrefs" package written by you.
Code runs well when the target is any Ahref url but gives internal billing error in output if I change URL to any other URL.

#target <- 'ahrefs.com'
target <- 'andrewgoldner.com'
temp <- rah_domain_rating(target, token = Sys.getenv("AHREFS_AUTH_TOKEN"),
     mode = "domain", metrics = NULL, limit = 1000, order_by = NULL,
     where = NULL, having = NULL)

Could you please help me with this? 

Thanks in Advance,

**Comment by Leszek-Sieminski** [comment] 2020-03-10 21:39
Hi Sayali!

First of all, thanks for using my package!

I suppose the problem is that your license give you access to Ahrefs but not the Ahrefs API. The Ahrefs API access isn't covered in regular subscription: [link to pricing](https://ahrefs.com/pricing). It requires additional API subscription: [link to API pricing](https://ahrefs.com/api/subscription).

You are able to download the data for "ahrefs.com" domain because the Ahrefs Team decided to make API requests for their own domain free so developers can easily test integrations. See this fragment in RAhrefs' readme:

![image](https://user-images.githubusercontent.com/32634801/76361730-e5471b80-631f-11ea-95fa-c4ec9429e65a.png)

However, my guess right now is that you need additional API subscription to download data for other domains and that's why you have this billing error.

Please let me know if this is the case. I am closing your issue but feel free to reopen it if you have both subscriptions and the problem lies in the package.

Best,
Leszek

**Closed as completed by Leszek-Sieminski** 2020-03-10 21:39 UTC

**Comment by sayalikardile** [comment] 2020-03-11 03:28
Perfect!
Thank you so much for the quick turnaround.
